name = "comentario-dm-samuelleite"
account_id = "ca55b550b5e0671cc0e3bd7594f32297"
main = "src/index.js"
compatibility_date = "2024-12-01"

[vars]
INSTAGRAM_ACCOUNT_ID = "17841401637880002"

# Secrets (configurados via `wrangler secret put`):
# INSTAGRAM_ACCESS_TOKEN
# INSTAGRAM_WEBHOOK_VERIFY_TOKEN

[[kv_namespaces]]
binding = "AUTOMATIONS"
id = "f0b16c16dd73402eba37427a504d5277"
